WebLibrary2/WebLibrary2.WebUI/Models/QueryRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebLibrary2.Domain.Concrete;
using WebLibrary2.Domain.Entity;
using WebLibrary2.Domain.Abstract;

namespace WebLibrary2.WebUI.Models
{
    public class QueryRepository
    {
        public QueryRepository()
        {
           
        }
       //static EFDbContext context = new EFDbContext();
       // public IQueryable<Books> queryBooks = from book in context.Books
       //                                       select book;


    }

}

WebLibrary2/WebLibrary2.WebUI/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebLibrary2.Domain.Abstract;


namespace WebLibrary2.WebUI.Controllers
{
    public class AuthorsController : Controller
    {
        private IAuthorsRepository repository;

        public AuthorsController(IAuthorsRepository authorRepository)
        {
            this.repository = authorRepository;
        }

        // GET: Authors
        public ViewResult Autors()
        {
            //ViewBag.Message = "Your application description page.";

            return View(repository.Authors);
        }
    }
}

WebLibrary2/WebLibrary2.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web.Mvc;
using WebLibrary2.Domain.Abstract;
using WebLibrary2.Domain.Concrete;
using WebLibrary2.Domain.Entity;
using System.Data.Entity;

namespace WebLibrary2.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private EFDbContext context = new EFDbContext();
              
        public ViewResult Index()
        {
            var books = context.Books.Include(p => p.Authors);
            return View(books.ToList());
        }

     
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

WebLibrary2/WebLibrary2.WebUI/Views/Authors/Autors.cshtml
@using WebLibrary2.Domain.Entity;
@model IEnumerable<Authors>
@{
    ViewBag.Title = "Авторы";
}

<h3>@ViewBag.Message</h3>
<div>
    <table>
        <tr>
            <th>
                <h4>Автор</h4>
            </th>
        </tr>
        @foreach (var author in Model)
        { 
        <tr>
            <td>
                <h4>@author.AuthorName</h4>
            </td>
        </tr>
        }
    </table>
</div>

<p>Use this area to provide additional information.</p>

WebLibrary2/WebLibrary2.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Mikhail Zelenskiy<br />
    <abbr title="Phone">P:</abbr>
    +380663035521
</address>

<address>
    <strong>Skype:</strong>zmisha0<br />
    <strong>Gmail:</strong> <a href="mailto:zelenskiymo@gmail.com">zelenskiymo@gmail.com</a>
</address>

WebLibrary2/WebLibrary2.WebUI/Views/Home/Index.cshtml
@using System.Data.Entity;
@using System.Linq.Expressions;
@model IEnumerable<WebLibrary2.Domain.Entity.Books>


@{
    ViewBag.Title = "List of books";
}

<div>
    <h2>Список книг</h2>
    <h4>
        @Html.ActionLink("Добавить книгу", "Authors");
    </h4>
    <br />

        <table>
            <tr>
                <th><h4>Автор</h4></th>
                <th><h4>Назнвание</h4></th>
                <th><h4>Жанр</h4></th>
                <th><h4>Год публикации</h4></th>
                <th><h4>Действие</h4></th>
            </tr>
            @foreach (var book in Model)
            {
                <tr>
                    <td><h4>@Html.DisplayFor(modelItem => book.Authors.AuthorName)</h4></td>
                    <td><h4>@Html.DisplayFor(modelItem => book.BookName)</h4></td>
                    <td><h4>@Html.DisplayFor(modelItem => book.GenreID)</h4></td>
                    <td><h4>@Html.DisplayFor(modelItem => book.YearOfPublish)</h4></td>

                    <td><h4>@Html.ActionLink("Редактировать", "Authors") |
                    @Html.ActionLink("Удалить", "Authors")</h4></td>

                    @**@
                   
                </tr>
            }
        </table>
    </div>

@*class="jumbotron"*@

WebLibrary2/WebLibrary2.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – библиотека ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Список книг", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Список авторов", "Autors", "Authors")</li>
                    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – библиотека ASP.NET</p>
            <p>Автор - Михаил Зеленский</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>